name: GitHub CI

on: [push, pull_request]

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

env:
  MODULE_NAME: nginx-stream-preread-str-module
jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        compiler: [clang-12, gcc-10]
        confargs: ["--add-module=./$MODULE_NAME", '--add-dynamic-module=./$MODULE_NAME']
    env:
      CC: ${{ matrix.compiler }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get update -qq
          sudo apt-get install -y \
            build-essential \
            clang-12 \
            gcc-10 \
            libssl-dev \
            libpcre3-dev \
            libxml2-dev \
            curl \
            unzip \
      - name : Build
        run: ./ci_build.sh ${{ matrix.confargs }}
      - name : Install
        run : |
          cd /tmp/builddir/nginx
          sudo make install
      - name : Test smoke
        run : /sbin/nginx -V
